### ISSUE TITLE
Versions >1.4.10 not starting

### ISSUE THREAD

**Issue by wbm37** [phpdocker-io/readability-js-server#29]
Environment:
rootless podman 4.6.2 on Fedora 39

Error:
```
2023-09-27T11:28:24: PM2 error: Error: ENOENT: no such file or directory, open '/home/readability/.pm2/module_conf.json'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at Configuration.getAllSync (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/Configuration.js:299:26)
    at Configuration.getSync (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/Configuration.js:270:30)
    at God.init (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/God.js:71:38)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/God.js:574:5)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
2023-09-27T11:28:24: PM2 log: Launching in no daemon mode
2023-09-27T11:28:24: PM2 error: Error: ENOENT: no such file or directory, open '/home/readability/.pm2/pm2.pid'
    at Object.openSync (node:fs:603:3)
    at Object.writeFileSync (node:fs:2324:35)
    at Daemon.innerStart (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/Daemon.js:91:8)
    at /usr/local/share/.config/yarn/global/node_modules/pm2/lib/Client.js:78:14
    at /usr/local/share/.config/yarn/global/node_modules/pm2/lib/Client.js:321:14
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

When I use version <1.5, such as 1.4.10, it works and starts without any error.

**Comment by luispabon** [comment]
How are you running it exactly? I can't reproduce it in docker:

![image](https://github.com/phpdocker-io/readability-js-server/assets/6388823/352f5424-47f8-4428-8df2-c9475282617f)

**Comment by wbm37** [comment]
I am trying it via `podman run docker.io/phpdockerio/readability-js-server:1.5`

`podman run docker.io/phpdockerio/readability-js-server:1.4.10` deploys fine.

oddly enough, `podman run docker.io/phpdockerio/readability-js-server:1.5` deploys fine via sudo. 

the difference between the two versions is mainly just dependencies, isn't it?

**Comment by wbm37** [comment]
passing `--user=root` to the podman run command seems to of fixed the issue.

Deploys Fine:
```
podman run docker.io/phpdockerio/readability-js-server:1.4 whoami
readability
```

Does not deploy:
```
podman run docker.io/phpdockerio/readability-js-server:1.5 whoami
readability
```

Deploys fine:
```
podman run --user=root docker.io/phpdockerio/readability-js-server:1.5 whoami
root
```

**Comment by luispabon** [comment]
it is very bizarre. Between the two versions you mentioned the only significant change was the node version (16-alpine to 18-alpine), but that could've come with an entirely new base alpine image that could have different filesystem attributes or something.  

As far as  I can see the readability process is being run by the readability user, and /home/readability is also owned by the same user.

Could you please paste here the output of the podman equivalent of

```
# as non root
docker run phpdockerio/readability-js-server:1.5 ls -la /home/ -R
```

Then, run the container normally as root and run the same thing within this same container, you'll need to docker exec into the running container.
